#!/bin/bash
set -e

# Path
SCRIPT_DIR=$(dirname "$(realpath $0)")
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)

# Intall Chakra (Use Chakra fork in ASTRA-Sim repo).
(
cd ${REPO_ROOT}/astra-sim/extern/graph_frontend/chakra
pip3 install .
# The checked-in Chakra Python bindings are generated by protobuf 7.35.
# Chakra's current package metadata still pins protobuf 6, which makes both
# the legacy subprocess converter and the in-process converter fail at import
# time. Keep the runtime on the same protobuf major as the generated code.
pip3 install 'protobuf>=7.35.0,<8'
)

# Compile ASTRA-sim with analytical backend model
(
cd ${REPO_ROOT}/astra-sim
ANALYTICAL_BUILD_SCRIPT=./build/astra_analytical/build.sh
if grep -q $'\r' "${ANALYTICAL_BUILD_SCRIPT}"; then
  bash -c "$(tr -d '\r' < "${ANALYTICAL_BUILD_SCRIPT}")" \
    "${ANALYTICAL_BUILD_SCRIPT}"
else
  bash "${ANALYTICAL_BUILD_SCRIPT}"
fi
)

# Compile ASTRA-sim with ns3 backend model
# (
# cd ${REPO_ROOT}/astra-sim
# bash ./build/astra_ns3/build.sh
# )
